### ISSUE TITLE
Readme Update

### ISSUE THREAD

**Issue by jsroyal** [libetl/soundtransform#65]
Please can you restructure readme and put a overview  of How you done and what dependency require and other thing created a document and put in document folder.
Thanks it will help.

**Comment by libetl** [comment]
Hi,

Please suggest me a proposal for a Table Of Content so I can understand what you would like to see.

**Comment by libetl** [comment]
Hi,
closing this comment for now. If you find something missing in this javadoc please tell me.
("How you done" : is that a code guideline doc ? and "what dependency require" : is it an install guide ?)
